DROP TABLE IF EXISTS FAKULTET CASCADE;
DROP TABLE IF EXISTS STATUS CASCADE;
DROP TABLE IF EXISTS DEPARTMAN CASCADE;
DROP TABLE IF EXISTS STUDENT CASCADE;

DROP SEQUENCE IF EXISTS fakultet_seq;
DROP SEQUENCE IF EXISTS status_seq;
DROP SEQUENCE IF EXISTS departman_seq;
DROP SEQUENCE IF EXISTS student_seq;


CREATE TABLE FAKULTET(
    ID INTEGER NOT NULL,
    NAZIV VARCHAR(100),
    SEDISTE VARCHAR(50)
    );
    
CREATE TABLE STATUS(
    ID INTEGER NOT NULL,
    NAZIV VARCHAR(100),
    OZNAKA VARCHAR(10)
    );
    
CREATE TABLE DEPARTMAN(
    ID INTEGER NOT NULL,
    NAZIV VARCHAR(100),
    OZNAKA VARCHAR(10),
    FAKULTET INTEGER NOT NULL
    );
    
CREATE TABLE STUDENT(
    ID INTEGER NOT NULL,
    IME VARCHAR(50) NOT NULL,
    PREZIME VARCHAR(50) NOT NULL,
    BROJ_INDEKSA VARCHAR(20) NOT NULL,
    STATUS INTEGER NOT NULL,
    DEPARTMAN INTEGER NOT NULL
    );
    
    
ALTER TABLE FAKULTET 
ADD CONSTRAINT pk_fakultet PRIMARY KEY (id);

ALTER TABLE STATUS 
ADD CONSTRAINT pk_status PRIMARY KEY (id);

ALTER TABLE DEPARTMAN 
ADD CONSTRAINT pk_departman PRIMARY KEY (id);

ALTER TABLE STUDENT 
ADD CONSTRAINT pk_student PRIMARY KEY (id);


ALTER TABLE DEPARTMAN 
ADD CONSTRAINT fk_departman_fakultet FOREIGN KEY (FAKULTET)
REFERENCES FAKULTET(ID) on delete cascade;

ALTER TABLE STUDENT
ADD CONSTRAINT fk_student_departman FOREIGN KEY(DEPARTMAN)
REFERENCES DEPARTMAN(ID) on delete cascade;

ALTER TABLE STUDENT
ADD CONSTRAINT fk_student_status FOREIGN KEY(STATUS)
REFERENCES STATUS(ID) on delete cascade;


CREATE INDEX idx_pk_status ON STATUS(id);
CREATE INDEX idx_pk_fakultet ON FAKULTET(id);
CREATE INDEX idx_pk_departman ON DEPARTMAN(id);
CREATE INDEX idx_pk_student ON STUDENT(id);

CREATE INDEX idx_fk_departman_fakultet ON DEPARTMAN(fakultet);
CREATE INDEX idx_fk_student_departman ON STUDENT(departman);
CREATE INDEX idx_fk_student_status ON STUDENT(status);

CREATE SEQUENCE IF NOT EXISTS FAKULTET_SEQ INCREMENT 1 START 1;
CREATE SEQUENCE IF NOT EXISTS DEPARTMAN_SEQ INCREMENT 1 START 1;
CREATE SEQUENCE IF NOT EXISTS STATUS_SEQ INCREMENT 1 START 1;
CREATE SEQUENCE IF NOT EXISTS STUDENT_SEQ INCREMENT 1 START 1;

Alter table Status alter column id
set default nextval('STATUS_SEQ');

Alter table fakultet alter column id
set default nextval('FAKULTET_SEQ');

Alter table departman alter column id
set default nextval('DEPARTMAN_SEQ');

Alter table student alter column id
set default nextval('STUDENT_SEQ');